### ISSUE TITLE
xcbuild Intermittent Fatal malloc() Error

### ISSUE THREAD

**Issue by wjk** [facebook/xcbuild#145]
On my system (macOS 10.12), `xcbuild` (or the `xcodebuild` tool installed by it, which I assume is synonymous) crashes with a fatal error deep within the system `malloc` library. This crash is intermittent (sometimes xcbuild launches just fine), but when it does happen, the crash is immediate. [Here is a sample crash log.](https://gist.github.com/wjk/603be9f548a308207e95ac4451c43402) Is there anything that can be done about this? I need to use `xcbuild` for my project because of its support for custom specification files (Apple `xcodebuild` does not support this as far as I know), and this crash is stopping me from being able to continue. Thanks!

**Comment by grp** [comment]
I've seen this too, but haven't been able to track it down, since it's intermittent and doesn't come up in the debugger.

Maybe try running with an ASAN build? You can uncomment the related lines in the root `CMakeLists.txt` and see if that gives more debugging information.

Other useful info would be what file xcbuild is reading when it crashes — it looks like it's an xcspec, but the log doesn't say which one. Turning on the logging in `Libraries/pbxspec/Sources/Manager.cpp` is verbose, but might help point to a specific file to test against.

**Comment by grp** [comment]
Found some more info with an ASAN build:

    grp$ ./build/dump_xcspec $(xcode-select --print-path)
    =================================================================
    ==11214==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6100000862f4 at pc 0x0001011c5c2e bp 0x7fff5f16eda0 sp 0x7fff5f16e560
    WRITE of size 360 at 0x6100000862f4 thread T0
        #0 0x1011c5c2d in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x41c2d)
        #1 0x1010690f5 in plist::Format::ReadData(void*, void*, unsigned long) Binary.cpp:117
        #2 0x10106c844 in plist::Format::Create(void*, _ABPRecordType, void*, void*, void*) Binary.cpp:199
        #3 0x1010366a7 in __ABPCreateObject(_ABPContext*, _ABPRecordType, void*, void*, void*) ABPCoderPrivate.h:174
        #4 0x1010376db in __ABPCreateString(_ABPContext*, long long, unsigned long, bool) ABPCoderPrivate.h:210
        #5 0x1010356ef in __ABPReadStringUnicode(_ABPContext*, unsigned long) ABPReader.cpp:178
        #6 0x101033caf in _ABPReadObject(_ABPContext*) ABPReader.cpp:304
        #7 0x10103397e in ABPReadObject ABPReader.cpp:415
        <trimmed>

Good place to start looking, will keep investigating.

**Comment by grp** [comment]
Let me know if you still see this, but I think it should be good now.
