### ISSUE TITLE
"Build file is missing file reference error" could be more useful

### ISSUE THREAD

**Issue by copumpkin** [facebook/xcbuild#156]
I'm running `xcbuild` against http://opensource.apple.com/source/Libc/Libc-1082.50.1/ and I get a lot of `error: build file is missing file reference` messages, but they don't convey information on what's missing and where. It would probably also make sense to change the message to say "warning" since it doesn't seem to stop the build.

This appears to be due to https://github.com/facebook/xcbuild/blob/master/Libraries/pbxbuild/Sources/Phase/File.cpp#L58. Not sure what fields would be useful to include in the error message!

**Comment by grp** [comment]
I don't seem to have the right SDK to build the project (missing some headers), but doing a dry-run build with the `macosx` SDK, saw those errors too.

Looks like it's caused by these entries in the `libc_eOS` target's sources build phase:

    C97A6F761517AF53005E1998 /* (null) in Sources */ = {isa = PBXBuildFile; };
    C97A6F761517AF53005E1998 /* (null) in Sources */ = {isa = PBXBuildFile; };
    C97A6F761517AF53005E1998 /* (null) in Sources */ = {isa = PBXBuildFile; };
    C97A6F761517AF53005E1998 /* (null) in Sources */ = {isa = PBXBuildFile; };

Which are missing an actual file to build. In the Xcode UI it looks like this:

<img width="441" alt="screen shot 2016-10-13 at 08 57 34" src="https://cloud.githubusercontent.com/assets/163390/19356608/3f0974b0-9123-11e6-8c87-1cea67f71208.png">

So: agree, this looks like it would be better as a warning, if that, rather than an error.

**Comment by copumpkin** [comment]
Cool, thanks @grp. I'm guessing it's probably some Apple internal redaction process pulling them out of there? The main context I can think of would be a line reference into the file, but that might be gone at the point where this is getting processed?

**Comment by grp** [comment]
Yeah, line references into the pbxproj would be long gone at that point. Xcode itself seems to just ignore it, but I think a warning is better. Easy enough to find under the target in the Xcode UI too.
