### ISSUE TITLE
Support JSON in plutil

### ISSUE THREAD

**Issue by copumpkin** [facebook/xcbuild#160]
It looks like the JSON parser and writer are already implemented. Not clear to me whether there's nontrivial work left or if it's just plugging the various bits and pieces into the pre-existing parsers and writers.

**Comment by grp** [comment]
Just plugging it in, mostly.

The slightly difficult part is that `plutil.cpp` was written using `plist::Format::Any` to store formats, and that (intentionally) doesn't support JSON since it's not a real plist format. So either `plist::Format::Any` needs to add JSON or `plutil.cpp` needs its own format abstraction that does as well.

**Comment by copumpkin** [comment]
> but implementing discriminated union in C++ like plist::Format::Any ends up being a lot of code

Clearly time to translate it all to Rust or Swift :)

**Comment by grp** [comment]
>  Rust or Swift :)

No Haskell? ;)
