### ISSUE TITLE
GNU-compatible specs

### ISSUE THREAD

**Issue by matthewbauer** [facebook/xcbuild#189]
Right now, the Linker specs assume that you are using Apple's libtool so if you run a GNU libtool you will get problems:

```
bash-4.3$ /nix/store/7alx3yp0xjsfaascai6wfa7h3m9pmhjk-nixpkgs.xctoolchain/usr/bin/clang -arch x86_64 -filelist ./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Intermediates/adv_cmds.build/Release-/whois.build/Objects-normal/x86_64/whois.LinkFileList -isysroot /nix/store/f9phbmvnwfsmp797p1vbj7xpi928d0w5-nix.nixpkgs.sdk -dead_strip -rpath /nix/store/c8mp7xl7k6vgi48r99ifjkqklx18flxi-adv_cmds/lib64 -rpath /nix/store/c8mp7xl7k6vgi48r99ifjkqklx18flxi-adv_cmds/lib -L/nix/store/wvfsisx6b969z297c3dkb2yikkqxiyfd-libc++-3.7.1/lib -F./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Products/Release- -Xlinker -dependency_info -Xlinker ./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Intermediates/adv_cmds.build/Release-/whois.build/Objects-normal/x86_64/whois_dependency_info.dat -o ./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Products/Release-/whois
<ependency_info.dat -o ./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Products/Release-/whois
clang-3.7: warning: argument unused during compilation: '-arch x86_64'
clang-3.7: warning: argument unused during compilation: '-dead_strip'
clang-3.7: warning: argument unused during compilation: '-F./adv_cmds-bcbdieruzwlfsscqwjvbjgsoswog/Build/Products/Release-'
/nix/store/yf7q8bz2a9idrn944y4zwpj2j40vx36p-binutils-2.27/bin/ld: -f may not be used without -shared
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps we can have two separate libtools? I don't think there is any way to get Apple libtool on a Linux machine.

**Comment by grp** [comment]
I mean, you can build it: it's part of Apple's cctools package. :)

The main issue is that libtool is confusingly named. Apple's libtool and GNU libtool have the same name but don't serve the same or even similar functions. You'll probably want either Apple's libtool built for Linux, assuming you're building for Darwin, or a script emulating it.

The latter isn't too hard to implement since the only thing libtool is used for is making static libraries. Parse out the  options (`libtool -static -o <output> -filelist <inputs> <input1...>`) and run `ar` and `ranlib` as appropriate.

**Comment by matthewbauer** [comment]
Okay, I was making this more difficult than it needs to be. We have a cctools package in nixpkgs and maybe that works on Linux.
