### ISSUE TITLE
CMake Error: Could not create named generator Ninja

### ISSUE THREAD

**Issue by appplemac** [facebook/xcbuild#47]
Getting this error while trying to build `xcbuild` on Linux:

```
ubuntu@box1507:~/ios9-examples-linux/xcbuild$ make
mkdir -p build
cmake -Bbuild -H. -G Ninja
CMake Error: Could not create named generator Ninja
make: *** [all] Error 1
```

I am on Ubuntu Precise, `ninja` version is `1.3.4`, `cmake` version is `2.8.7`, GCC version is `5.2.1 20151031`, `libxml2-dev` is `2.7.8`. Am I missing something?

**Comment by grp** [comment]
This seems likely due to an old version of CMake. I think xcbuild will work best with CMake 3.1 or later. 

Depending on your version of Ubuntu, the system packages may be wildly outdated, but you should be able to install it yourself. If you look at the Travis config, it adds a custom repository for a newer CMake package that might work.

**Comment by appplemac** [comment]
That was it. Thank you!
