### ISSUE TITLE
xcbuild significantly slower than xcodebuild

### ISSUE THREAD

**Issue by keith** [facebook/xcbuild#91]
After getting `xcbuild` working with our project, I noticed that the timing didn't line up as I expected for builds, and especially incremental builds. Here are the commands I ran:

```
$ rm -rf ~/Library/Developer/Xcode/DerivedData/
$ time xcbuild -executor ninja -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug -sdk iphonesimulator
xcbuild -executor ninja -workspace Lyft.xcworkspace  Lyft  1573.94s user 239.40s system 208% cpu 14:27.91 total
$ time xcbuild -executor ninja -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug -sdk iphonesimulator
xcbuild -executor ninja -workspace Lyft.xcworkspace  Lyft  89.94s user 7.74s system 72% cpu 2:14.49 total

$ rm -rf ~/Library/Developer/Xcode/DerivedData/
$ time xcodebuild -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug -sdk iphonesimulator
xcodebuild -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug  1587.91s user 286.77s system 501% cpu 6:14.02 total
$ time xcodebuild -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug -sdk iphonesimulator
xcodebuild -workspace Lyft.xcworkspace -scheme Lyft -configuration Debug  9.65s user 1.96s system 142% cpu 8.138 total
```

The immediate thing I noticed that seemed out of place, was that even for incremental builds with `xcbuild`, it seems to attempt to compile each file, and then output `"skipped"` for each one. Even though it isn't doing that work, this seems to take up a significant amount of time.

I wouldn't be surprised if we had some interesting configuration issues that also caused this.

Let me know what other info I can provide to make this useful.

**Comment by grp** [comment]
I think the `"skipped"` output is expected. The way Swift incremental compilation works is that the build system calls `swiftc` for a whole module, which itself handles determining which files need to be rebuilt. That's a consequence of Swift allowing files within modules to have undeclared dependencies on code from other files in the module.

`xcodebuild` does compiles whole modules, but it parses the `swiftc` output to hide it from the console and present it as if it was scheduling the `swiftc` subtasks itself. This also means that `xcbuild` can't be as much faster for Swift as it is for C-based languages, since a majority of the scheduling is happening *within* a Ninja rule, rather than between them. So the full-build time being about even seems reasonable, although the CPU utilization difference between them is slightly suspect.

For incremental builds, I can't think of any reason it should be 10x slower, though. Perhaps the issue is that `xcbuild` should be able to avoid even running `swiftc` at all for targets where *none* of the inputs have changed, and that isn't working for some reason? That seems plausible based on what you said, since a no-change incremental build shouldn't run `swiftc` at all but you noted seeing `swiftc` output...

One useful feature for debugging overbuilding is Ninja's `-d explain` flag. It's similar to the (undocumented) `ExplainWhyBuildCommandsAreRun` defaults key for Xcode, in that it explains why the build system decided to re-run a command. With `xcbuild`, the easiest way to use it is by running Ninja manually:

    $ xcbuild -executor ninja -generate [...]
    Generating Ninja files...
    Wrote Ninja: <path>/build.ninja

Then run Ninja with the debug option enabled:

    $ ninja -f <path>/build.ninja -d explain

There's also a `-d stats` which might be useful to paste in case the overhead is coming from Ninja itself. (I remember some of that at Facebook, which had an extremely large number of files to compile and consequently large Ninja files, but I don't think that would impact a Swift project as much.)
